version: '3.8'

services:
  php-docker-app:
    build: .
    container_name: php-docker-app
    ports:
      - "8101:8101"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql1
    networks:
      - app-network

  mysql1:
    image: mysql:latest
    container_name: mysql_container2
    environment:
      MYSQL_ROOT_PASSWORD: password223
      MYSQL_DATABASE: my_db
    ports:
      - "3307:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - app-network 

volumes:
  mysql_data:

networks:
  app-network:
